[console]
enable = true
level = "INFO"
console_format = "%(asctime)s - %(filename)s:%(lineno)d - %(message)s"

[file]
enable_file_logging = true
log_file = "logs/mp2i.log"
file_format = "%(asctime)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"

[discord]
enable_discord_logging = true
discord_webhook = "https://discord.com/api/webhooks/<URL>"
discord_format = "%(asctime)s - %(filename)s:%(lineno)d\n%(message)s"

[ai]
enabled = true
allowed_channels = []
model = "community/vendouple/muse-glimmer-30b:free"
api_url = "https://gen.pollinations.ai/v1"
system_prompt = "Tu es le bot du serveur Discord de la classe MP2I. Tu es utile mais avec un ton sarcastique et humoristique en français. Réponds de manière concise, en français sauf si on te demande autre chose."
