[project]
name = "MP2I"
version = "0.1.0"
description = "Discord bot for our MP2I class"
readme = "README.md"
authors = [
    { name = "YoannDev90", email = "yoanndev@outlook.fr" },
    { name = "Elnix90", email = "elnix9@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "discord.py>=2.3.0",
    "python-dotenv>=1.0.0",
    "colorama>=0.4.6",
    "requests>=2.31.0",
    "openai>=1.30.0",
    "json5>=0.9.0",
    "aiohttp>=3.9.0",
    "Pillow>=10.0.0",
    "pilmoji>=2.0.0",
    "cairosvg>=2.7.0",
    "pytesseract>=0.3.10",
    "fastmcp>=2.0.0",
    "cocoindex>=1.0.0",
    "pint>=0.24.0"
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["main", "bot"]

[tool.setuptools.packages.find]
exclude = ["assets*", "data*", "scripts*"]

[dependency-groups]
dev = [
    "ruff>=0.9.0",
    "pre-commit>=4.0.0",
    "isort==9.0.1",
    "removestar==1.5.2",
    "pyright>=1.1.414",
]

[tool.isort]
profile = "black"
line_length = 200

[tool.ruff.lint]
ignore = ["BLE001", "S110"]
exclude = ["**/*.json5"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["I001"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff]
line-length = 200
