CREATE TABLE IF NOT EXISTS NOTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    note INTEGER,
    ds INTEGER
);

CREATE IF NOT EXISTS idx_ds ON NOTES(ds)

CREATE TABLE IF NOT EXISTS DS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);
