-- notes_shema
CREATE TABLE IF NOT EXISTS DS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    note REAL NOT NULL,
    ds INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ds ON NOTES (ds);
